version: '3.9'

services:
  myapplication:
    image: backend
    environment:
      - RUNTIME_ENV=staging
      - MONGODB_DB=staging
      - MONGODB_HOST=mongodb
      - MONGODB_USER=citizix
      - MONGODB_PASSWORD=S3cret
      - MONGODB_CA_CERT=/usr/local/share/ca-certificates/mongodb-cert.crt
      - ACCESS_TOKEN_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - O2_REDIS_HOST=cache
      - O2_REDIS_PORT=
    volumes:
      - ./ca-certs:/usr/local/share/ca-certificates
    ports:
      - "80:80"
    links:
      - cache
  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    command: [ "--sslMode", "requireSSL", "--sslPEMKeyFile", "/usr/local/share/ca-certificates/mongodb.pem" ]
    volumes:
      - ./ca-certs:/usr/local/share/ca-certificates
      - ~/apps/mongo4:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret

  cache:
    image: redis:alpine
#    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

